//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dog()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int id { get; set; }
        public int owner_id { get; set; }
        public string name { get; set; }
        public Nullable<int> experience { get; set; }
        public Nullable<System.DateTime> last_trained { get; set; }
        public Nullable<System.DateTime> date_gotten { get; set; }
        public Nullable<int> enchantment { get; set; }
        public Nullable<int> dog_class { get; set; }
        public Nullable<int> health { get; set; }
        public Nullable<int> atk_power { get; set; }
        public Nullable<int> defense { get; set; }
        public Nullable<int> prayer { get; set; }
        public Nullable<int> will { get; set; }
        public Nullable<int> intelligence { get; set; }
        public string image_path { get; set; }
        public string origin { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
